### ISSUE TITLE
items of projects are not showing in the "projects" view

### ISSUE THREAD

**Issue by mszyld** [MartinSzyld/Personal-Website-by-Projects#2]
Each project has an array "items" which I checked in the console that exists and has the required items. I tried to do a nested ngFor inside the ngFor that shows the projects to show these items, but it's not showing anything.

**Comment by natron2244** [comment]
Two things I see:
1. The all projects in `projects` variable don't have an items
2.  Once adding the item they are rendered off screen, try using find in the incept to see the element in the dom

One additional note, declare arrays generally like `PersonalWorkItem[]` rather then Array<PersonalWorkItem>

**Comment by natron2244** [comment]
To fix you will want to make sure that the items are with in the div marked with `slot="content"`
