### ISSUE TITLE
Create components for the three list

### ISSUE THREAD

**Issue by natron2244** [MartinSzyld/Personal-Website-by-Projects#3]
Create a component for the three types of list so you can clean up `home.page.html`. 

Example html output after:
```
<div [ngSwitch]="selectedSegment" class="list-container">
	<article-list *ngSwitchCase="articles" [articles]="articles" ></article-list>
	<talk-list *ngSwitchCase="talks" [talks]="talks" ></talk-list >
	<project-list *ngSwitchCase="projects" [projects]="projects" ></project-list >
</div>
```

**Comment by natron2244** [comment]
For reading:
https://angular.io/api/common/NgSwitchCase
https://angular.io/guide/component-overview

**Comment by mszyld** [comment]
I did something similar. I created components for the articles, preprints, and talks, so that they could be reused for the projects :)

**Comment by natron2244** [comment]
This will do for now, I will comments in the PR for suggested changes.
