### ISSUE TITLE
avoid duplicate definitions

### ISSUE THREAD

**Issue by mszyld** [MartinSzyld/Personal-Website-by-Projects#4]
The definitions of the data structures (Article, Talk, etc) and the related functions (isArticle, isTalk, etc) are repeated in the code for each of the modules/components. I should create a "service" that can be imported to each of these components to avoid duplicating the code

**Comment by mszyld** [comment]
I could do this for the data structures in "DataDefinitions.ts", but not for the functions, which appear both in homepage.ts and project.item.component.ts

**Comment by natron2244** [comment]
I suggest creating an interface.ts file that has all interfaces and helper methods in it
